Создал Makefile и внес соответствующие изменения в документацию
Ignasiya/chtune-social pull request #4
Opened 2024-05-04 18:59 UTC by Ignasiya

2024-05-04 20:54 UTC, paulmixxx requested changes

2024-05-04 20:54 UTC, paulmixxx commented on Makefile
> +export APP_NAME=chtune-social
В Makefile переменные окружения определяются по-другому
```
CUSTOM_IMAGE_TAG := 'v1.0.0' # определяет переменную в момент запуска команды make (рекомендуемый способ)
CUSTOM_IMAGE_TAG = 'v1.0.0' # определяет переменную в момент вызова этой переменной
```
Но если честно, не уверено что в данном случае вообще нужно определять `APP_NAME` и `DOCKER_COMPOSE_FILE`. 

`APP_NAME` - это для лары?

2024-05-04 20:54 UTC, paulmixxx commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Здесь в принципе всё ок сделал, но на не очень мощных пк могут быть траблы с запуском миграций. Дело в том, что БД нужно какое-то время для запуска и если БД еще не успеет запустится, на этапе миграций установка упадет. Чтобы это предотвратить, нужно добавить шаг с проверкой готовности базы. Я в свое время писал такой скрипт для mariadb, возьми его за основу, подправь для mysql и добавь перед запуском миграций.
```
wait-db:
	while ! (docker-compose exec db bash -c 'mariadb -hlocalhost -P3306 -uroot -p$$MARIADB_ROOT_PASSWORD -e "USE $$MARIADB_DATABASE; SHOW TABLES;"'); do echo "\n sleep 1 min..."; sleep 60; done;
	echo "DB is ok!"
```

2024-05-04 20:54 UTC, paulmixxx commented on src/.env.example
> +DB_ROOT_PASSWORD=root
А нужен ли тут рут?

2024-05-05 06:40 UTC, Ignasiya commented on src/.env.example
> +DB_ROOT_PASSWORD=root
Честно говоря, взял его с .env Laravel, но до сих пор не понимаю зачем он нужен даже там, ведь подключение идет по логину и паролю.

2024-05-05 06:41 UTC, Ignasiya commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Круто, а ведь можно наверно отдельный скрипт в команды artisan запихнуть?

2024-05-05 06:41 UTC, Ignasiya commented on Makefile
> +export APP_NAME=chtune-social
Взял с образца в инете, теперь понимаю, что тут не имеет смысла их писать

2024-05-05 07:25 UTC, Ignasiya commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Дает ошибку: ERROR 1045 (28000): Access denied for user '-p'@'localhost' (using password: NO)
почему-то не хочет подтянуть данные из окружения .env

2024-05-05 16:30 UTC, paulmixxx commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Переменные окружения правильные подставляешь?

2024-05-05 16:44 UTC, paulmixxx commented on src/.env.example
> +DB_ROOT_PASSWORD=root
https://github.com/laravel/laravel/blob/11.x/.env.example

```
DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=laravel
# DB_USERNAME=root
# DB_PASSWORD=
```

Вроде, не используется. Проверь, если без этой переменной работает, можно удалять. Рут обычно для администрирования нужен, для проекта обычного юзера достаточно.

2024-05-05 16:44 UTC, paulmixxx commented on docker-compose.yaml
> -      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
Вот тут рут лучше оставить, а в самом проекте он не нужен.

2024-05-05 16:44 UTC, paulmixxx commented on docker-compose.yaml
>        MYSQL_ALLOW_EMPTY_PASSWORD: 1
А это наоборот посоветовал бы убрать. Лучше пусть пароль будет определен.

2024-05-05 16:44 UTC, paulmixxx commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Проверь наличие нужных переменных внутри контейнера командой `env`

2024-05-05 17:03 UTC, Ignasiya commented on Makefile
> +init: init-env up composer-install npm-install prepare migrate
Протупил с .env - оказывается docker подтягивает из своего environment MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD вместо файла .env.

2024-05-05 17:12 UTC, Ignasiya commented on docker-compose.yaml
>        MYSQL_ALLOW_EMPTY_PASSWORD: 1
Поправил

2024-05-05 17:13 UTC, Ignasiya commented on docker-compose.yaml
> -      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
Поправил

2024-05-05 17:26 UTC, paulmixxx approved these changes

2024-05-05 17:28 UTC, merged